//! End-to-end tests of `microprice evaluate-parquet`.
//!
//! The tiny Parquet fixtures are generated inside the tests, from the
//! deterministic *synthetic* generator, using the same writer the data crate
//! exposes. They prove the file -> ingest -> calibrate -> evaluate -> report
//! path and its failure modes; the numbers mean nothing about real markets.

use std::process::{Command, Output};

fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_microprice"))
        .args(args)
        .output()
        .unwrap()
}

/// Without the feature the subcommand must exist and explain itself, not
/// crash or pretend. (Compiled only in default-feature builds.)
#[cfg(not(feature = "parquet"))]
#[test]
fn without_the_feature_the_subcommand_explains_how_to_enable_it() {
    let out = run(&["evaluate-parquet", "--input", "x.parquet"]);
    assert!(!out.status.success());
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("--features parquet"), "{err}");
}

#[cfg(feature = "parquet")]
mod with_feature {
    use super::run;
    use microprice_core::{BookEvent, BookValidationPolicy, PriceTicks, SymbolId, TopOfBook};
    use microprice_data::{
        write_events_to_parquet, MarketDataSource, SyntheticConfig, SyntheticEventGenerator,
    };
    use std::path::PathBuf;

    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("mp-cli-pq-{}-{name}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// Synthetic events with prices doubled (half-tick units, so the file
    /// is meant to be read with `--resolution 2`) and timestamps 10 ms apart.
    fn fixture_events(n: usize) -> Vec<BookEvent> {
        let mut g = SyntheticEventGenerator::new(SyntheticConfig {
            symbol: SymbolId(1),
            initial_mid_ticks: 10_000,
            initial_spread_ticks: 2,
            initial_bid_qty: 500,
            initial_ask_qty: 500,
            arrival_rate: 0.3,
            cancel_rate: 0.2,
            market_order_rate: 0.2,
            imbalance_persistence: 0.5,
            price_move_probability: 0.1,
            seed: 5,
        })
        .unwrap();
        (0..n)
            .map(|i| {
                let e = g.next_event().unwrap();
                BookEvent {
                    timestamp_ns: 1_700_000_000_000_000_000 + i as u64 * 10_000_000,
                    sequence: i as u64,
                    symbol: SymbolId(1),
                    book: TopOfBook::new(
                        PriceTicks(e.book.bid_price.0 * 2),
                        e.book.bid_qty,
                        PriceTicks(e.book.ask_price.0 * 2),
                        e.book.ask_qty,
                        BookValidationPolicy::RejectCrossedAndLocked,
                    )
                    .unwrap(),
                }
            })
            .collect()
    }

    fn base_args<'a>(path: &'a str, extra: &[&'a str]) -> Vec<&'a str> {
        let mut a = vec![
            "evaluate-parquet",
            "--input",
            path,
            "--horizons",
            "1,5",
            "--primary-horizon",
            "5",
            "--bootstrap-resamples",
            "0",
        ];
        a.extend_from_slice(extra);
        a
    }

    #[test]
    fn end_to_end_report_states_its_sample_sizes_and_shares_the_decision_rule() {
        let dir = scratch("e2e");
        let path = dir.join("l1.parquet");
        write_events_to_parquet(&fixture_events(4000), &path).unwrap();
        let report = dir.join("out").join("report.md");
        let mut args = base_args(
            path.to_str().unwrap(),
            &[
                "--wall-clock-horizons-ms",
                "50",
                "--report-md",
                report.to_str().unwrap(),
            ],
        );
        args.extend(["--symmetrize"]);
        let out = run(&args);
        assert!(
            out.status.success(),
            "{}",
            String::from_utf8_lossy(&out.stderr)
        );
        let text = std::fs::read_to_string(&report).unwrap();
        assert!(text.contains("Generated by `microprice evaluate-parquet`"));
        assert!(text.contains("format: Parquet (microprice schema)"));
        assert!(text.contains("rows read: 4000"));
        assert!(text.contains("events accepted: 4000"));
        assert!(text.contains("2800 train events, 1200 test events"));
        assert!(text.contains("### Horizon 1 events"));
        assert!(text.contains("### Wall-clock horizon 50 ms"));
        assert!(text.contains("Pre-registered decision (primary horizon 5)"));
        // --symmetrize is still labelled exploratory through this path.
        assert!(text.contains("EXPLORATORY"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn default_configuration_matches_evaluate_csv_on_the_same_events() {
        // Same events through Parquet and through a generic CSV must give
        // the same calibration and losses: the two paths share one core.
        let dir = scratch("parity");
        let events = fixture_events(3000);
        let pq = dir.join("l1.parquet");
        write_events_to_parquet(&events, &pq).unwrap();
        let mut csv = String::from("timestamp,bid_price,bid_qty,ask_price,ask_qty\n");
        for e in &events {
            // Model units / 2 = ticks; tick 1.0 so the CSV path's grid is ticks.
            csv.push_str(&format!(
                "{},{},{},{},{}\n",
                e.timestamp_ns / 1_000_000,
                e.book.bid_price.0 as f64 / 2.0,
                e.book.bid_qty.0,
                e.book.ask_price.0 as f64 / 2.0,
                e.book.ask_qty.0
            ));
        }
        let csv_path = dir.join("l1.csv");
        std::fs::write(&csv_path, csv).unwrap();

        let a = run(&base_args(pq.to_str().unwrap(), &[]));
        let b = run(&[
            "evaluate-csv",
            "--input",
            csv_path.to_str().unwrap(),
            "--tick-size",
            "1.0",
            "--qty-decimals",
            "0",
            "--horizons",
            "1,5",
            "--primary-horizon",
            "5",
            "--bootstrap-resamples",
            "0",
        ]);
        assert!(a.status.success() && b.status.success());
        let (a, b) = (
            String::from_utf8_lossy(&a.stdout).into_owned(),
            String::from_utf8_lossy(&b.stdout).into_owned(),
        );
        let table = |t: &str| -> Vec<String> {
            t.lines()
                .filter(|l| l.starts_with("| naive mid") || l.starts_with("| micro-price"))
                .map(str::to_string)
                .collect()
        };
        assert!(!table(&a).is_empty());
        assert_eq!(table(&a), table(&b));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn max_events_truncates_and_says_so() {
        let dir = scratch("max");
        let path = dir.join("l1.parquet");
        write_events_to_parquet(&fixture_events(1000), &path).unwrap();
        let out = run(&base_args(path.to_str().unwrap(), &["--max-events", "400"]));
        assert!(out.status.success());
        let text = String::from_utf8_lossy(&out.stdout);
        assert!(text.contains("rows read: 1000"));
        assert!(text.contains("events accepted: 400"));
        assert!(text.contains("**truncated**"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn bad_inputs_fail_with_clear_errors() {
        let dir = scratch("bad");
        // Missing file.
        let out = run(&base_args("/nonexistent/x.parquet", &[]));
        assert!(!out.status.success());
        assert!(String::from_utf8_lossy(&out.stderr).contains("Parquet I/O error"));

        // Not a Parquet file.
        let junk = dir.join("junk.parquet");
        std::fs::write(&junk, "timestamp,bid\n1,2\n").unwrap();
        let out = run(&base_args(junk.to_str().unwrap(), &[]));
        assert!(!out.status.success());
        assert!(String::from_utf8_lossy(&out.stderr).contains("error:"));

        // Decreasing timestamp at row 2 (rows are otherwise valid).
        let mut events = fixture_events(300);
        events[2].timestamp_ns = events[1].timestamp_ns - 1;
        let p = dir.join("time.parquet");
        write_events_to_parquet(&events, &p).unwrap();
        let out = run(&base_args(p.to_str().unwrap(), &[]));
        assert!(!out.status.success());
        let err = String::from_utf8_lossy(&out.stderr);
        assert!(
            err.contains("row 2") && err.contains("timestamp_ns"),
            "{err}"
        );

        // Repeated sequence number at row 3.
        let mut events = fixture_events(300);
        events[3].sequence = events[2].sequence;
        let p = dir.join("seq.parquet");
        write_events_to_parquet(&events, &p).unwrap();
        let out = run(&base_args(p.to_str().unwrap(), &[]));
        assert!(!out.status.success());
        let err = String::from_utf8_lossy(&out.stderr);
        assert!(err.contains("row 3") && err.contains("sequence"), "{err}");

        // Too few events.
        let p = dir.join("tiny.parquet");
        write_events_to_parquet(&fixture_events(20), &p).unwrap();
        let out = run(&base_args(p.to_str().unwrap(), &[]));
        assert!(!out.status.success());
        assert!(String::from_utf8_lossy(&out.stderr).contains("too few"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
